# Generated by Django 2.1.5 on 2019-02-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_closed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
