# Generated by Django 2.1.5 on 2019-02-02 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_ticket_date_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('created', models.DateField(default=datetime.date.today)),
                ('ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='issues.Ticket')),
            ],
        ),
    ]
