// Common
export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const LOGOUT = "LOGOUT";
export const LOGIN_ERROR = "LOGIN_ERROR";


// UX actions
export const OPEN_LOGIN = "OPEN_LOGIN";
export const CLOSE_LOGIN = "CLOSE_LOGIN";
export const OPEN_SIGNUP = "OPEN_SIGNUP";
export const CLOSE_SIGNUP = "CLOSE_SIGNUP";

// Issues
export const CREATE_ISSUE = "CREATE_ISSUE";
export const FETCH_ISSUES = "FETCH_ISSUES";
export const FETCH_ISSUE_DETAIL = "FETCH_ISSUE_DETAIL";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const UPVOTE = "UPVOTE";
export const CLOSE_ISSUE = "CLOSE_ISSUE";
export const REOPEN_ISSUE = "REOPEN_ISSUE";
export const FETCH_MY_ISSUES = "FETCH_MY_ISSUES";
export const FETCH_ISSUES_ASSIGNED_TO_ME = "FETCH_ISSUES_ASSIGNED_TO_ME";

export const FETCH_TOP_VOTED_FEATURES = "FETCH_TOP_VOTED_FEATURES";
export const ISSUE_DETAIL = "ISSUE_DETAIL";
export const CREATE_ISSUE_FAILED = "CREATE_ISSUE_FAILED";
export const FETCH_FEATURES = "FETCH_FEATURES";
export const FETCH_FEATURES_FAILED = "FETCH_FEATURES_FAILED";
export const FETCH_BUGS = "FETCH_BUGS";
export const FETCH_BUGS_FAILED = "FETCH_BUGS_FAILED";

// Dashboard
export const FETCH_DASHBOARD_DATA = "FETCH_DASHBOARD_DATA";
